application:
  port: 5000

database:
  username: "<your_db_username>"
  password: "<your_db_password>"
  port: <your_db_port>
  host: "<your_db_host>"
  database_name: "<your_db_name>"
  require_ssl: false

redis:
  uri: "<your_redis_uri>"
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60

email:
  host: "smtp.gmail.com"
  host_user: "**"
  host_user_password: "**"

